### ISSUE TITLE
prevent case sensitive

### ISSUE THREAD

**Issue by avishayhajbi** [stefanocudini/bootstrap-list-filter#13]
hii
is it possible to filter without case sensitive ?
a -- give me Avi
BUT
avi -- does give me Avi

i am tried to use       
itemFilter: function(text, item){  /* changing the item */  },
but it doesn't work !! 

thanks.

**Comment by stefanocudini** [comment]
solved it from versino 0.2.1
https://github.com/stefanocudini/bootstrap-list-filter/commit/48c55d6a0321546b345f81baf72c901d9498810c

**Comment by avishayhajbi** [comment]
sorry but i am updated my question . i had a mistake.
a -- give me Avi
BUT
avi -- does NOT give me Avi

casesensitive

did not works for me

**Comment by stefanocudini** [comment]
casesensitive is default to false
