### ISSUE TITLE
Similar to issue #8, itemChild does not work in my case using bootstrap collapsible list group

### ISSUE THREAD

**Issue by kevkha** [stefanocudini/bootstrap-list-filter#17]
Similar to issue #8 in my case <code>itemChild: 'h5, small',</code> does not seem to work. If I use one of them it works like charm. Does <b>itemChild</b> support class as selector? I tried <code>itemChild: '.list-group-item-head, .list-group-item-subhead',</code> without success. Thanks in advance.

``` html
<div class="panel list-group" id="mylist">
    <a href="#" class="list-group-item" data-toggle="collapse" data-target="#targetID" data-parent="#dataParent">
        <h5 class="list-group-item-head">Head</h5>
        <span class="list-group-item-subhead"><small>Subhead</small></span>
    </a>
    <div id="targetID" class="sublinks collapse">
        <!-- more code here -->
    </a>
</div>
```

``` javascript
$('#mylist').btsListFilter('#filterinput', {
    itemChild: 'h5, small',
    resetOnBlur: false,
    initial: false
});
```

**Comment by stefanocudini** [comment]
Where do you use it? do you have a public url?

**Comment by kevkha** [comment]
I created an example here http://jsfiddle.net/kevkha/wtyrzv3u/
Try to filter the color name in Head and Subhead. Thanks.

**Comment by stefanocudini** [comment]
for now this plugin doesn't support multiple child selector... wait for this solution or you can try to implement it.
Stefano

**Comment by stefanocudini** [comment]
@kevkha  do you solve the problem?
