### ISSUE TITLE
Ability to clear filter input with a button

### ISSUE THREAD

**Issue by kevkha** [stefanocudini/bootstrap-list-filter#18]
I have a button to clear the filter input. The input's value is clear but it does not trigger the event until I actually click on the input and press a backspace key.

**Comment by kevkha** [comment]
I created this workaround to simulate a backspace key press and it seems to work.
```javascript
	$(document).on('click','button.input-clear',function() {
		$(this).closest('div').find('input[type=search]').val('');
		var e = jQuery.Event('keyup', { keyCode: 8 });
		$(this).closest('div').find('input[type=search]').trigger(e);
	});
```

**Comment by stefanocudini** [comment]
I'm juyst added this new feature, try it here:
http://labs.easyblog.it/bootstrap-list-filter/examples/cancel-button.html

**Comment by kevkha** [comment]
Very :+1: Thanks!
