### ISSUE TITLE
Cancel Button not working

### ISSUE THREAD

**Issue by DeastinY** [stefanocudini/bootstrap-list-filter#19]
Hi, I added the bootstrap-list-filter.src.js and made the changes to the html.
Everything works as expected, but the cancel button.
Somehow the click doesn't work.
Did I forget anything ?

-----------

Furthermore pressing enter clears the search :)

**Comment by diddi-** [comment]
It seems that the form-control-feedback class has changed in bootstrap 3.3, https://github.com/twbs/bootstrap/pull/14104

quick fix is to add the pointer-events CSS with `cancelEl$.css({'pointer-events': 'auto'});` on line 79 in bootstrap-list-filter.src.js (this is immediately after the code that adds `top: 0` CSS to the cancel button). 

Not sure if that is the best way or if it introduces other issues, but it's working good for me at least.

**Comment by dmuth** [comment]
+1
