### ISSUE TITLE
Not Filter when Include Other Plugin

### ISSUE THREAD

**Issue by mehmetalidumlu** [stefanocudini/bootstrap-list-filter#20]
Hi,

I can't use multipleselect plugin with your ListFilter. When i call multiple select plugin then your plugin not filter query. But when i type an invalid query then i see "NoResult" message. Can you help me?

**Comment by stefanocudini** [comment]
what is multipleselect plugin?

**Comment by mehmetalidumlu** [comment]
Sorry,  it shoud've been Multiselect instead of "multipleselect", I have misspell. 

https://github.com/davidstutz/bootstrap-multiselect

**Comment by stefanocudini** [comment]
these are two different plugins and 'normal that are not compatible when applied to the same page elemendo
