### ISSUE TITLE
Meteor package need to be updated (> 0.9.0)

### ISSUE THREAD

**Issue by snajjar** [stefanocudini/bootstrap-list-filter#21]
Hello !

I really would like to use bootstrap-list-filter, but using it through meteor install is failing.

W20160104-16:55:42.371(1)? (STDERR) The package mrt:bootstrap-list-filter at 0.0.4 is incompatible with Meteor 0.9.0 or later.

Could we have an update on this?

Thank you!

**Comment by stefanocudini** [comment]
hi @snajjar maybe now it work
