### ISSUE TITLE
Disable form submission

### ISSUE THREAD

**Issue by finalwebsites** [stefanocudini/bootstrap-list-filter#26]
Hi,

I like your plugin very much and I use it for several websites :)
Thanks for sharing!

I've noticed that some people always hit the enter button to execute a search, even if there is no button :)
Right now I'm using this code to disable the form submission:

`
$('.searchform').on('keyup keypress', function(e) {
  var keyCode = e.keyCode || e.which;
  if (keyCode === 13) {
    e.preventDefault();
    return false;
  }
});
`

Maybe it's something you like to add to your plugin?

**Comment by stefanocudini** [comment]
ye sure... please send me a pull request!

**Comment by finalwebsites** [comment]
actually I use that code in my theme right now, didn't tried to add the code to your plugin :(

**Comment by stefanocudini** [comment]
@finalwebsites can you paste here new code... please?

**Comment by finalwebsites** [comment]
@stefanocudini I use the code in my initial post on this issue (in a general JS file).

I didn't changed the plugin code.

**Comment by stefanocudini** [comment]
ok tnk
