### ISSUE TITLE
bootstrap-list-filter.js is not working

### ISSUE THREAD

**Issue by nastia-shaternik** [stefanocudini/bootstrap-list-filter#33]
Hi @stefanocudini 

I'm trying to make use of `bootstrap-list-filter`.

As I understood it can perform basic search through RegExp.
I've tried to use it as you propose in your README but unfortunately it doesn't work.

What I'm doing wrong?

Thanx in advance for your response.

PS bootstrap and jquery were included, and I don't see any errors in console log.

**Comment by stefanocudini** [comment]
You probably did not include all the necessary css
