### ISSUE TITLE
Enhancement: Post Filter Event

### ISSUE THREAD

**Issue by AlirezaAReadifarian** [stefanocudini/bootstrap-list-filter#35]
Hi,
I recently used this awesome tool and made a few enhancements. I am more than happy if I can contribute.

One enhancement was adding event 'filtered'. The even fires right after list gets filtered. This comes in handy in cases when taking a post filter action is required. For example, in my case, I needed to show the number of available items after filtering had been done.

If this is confirmed, I can make a PR straight away.

**Comment by stefanocudini** [comment]
yes ok! Attention to the conflicts! 

Thank you @AlirezaAReadifarian
