### ISSUE TITLE
Select item with up and down arrows and enter

### ISSUE THREAD

**Issue by epicserve** [stefanocudini/bootstrap-list-filter#36]
Is there a way to make it so you can select items using the up and down arrow keys and then hit enter to have it go to a URL?

**Comment by stefanocudini** [comment]
no @epicserve for now..
It's great idea!
I'm sorry but I haven't more free time.
But probably you can try to fork this plugin and integrate this beahviour using it self code:
https://github.com/stefanocudini/leaflet-search/blob/master/src/leaflet-search.js#L662
