### ISSUE TITLE
bootstrap dependency install the second bootstrap module

### ISSUE THREAD

**Issue by Tolsi** [stefanocudini/bootstrap-list-filter#5]
I have used in my project package ```mizzao: bootstrap-3``` and after the installation of this package some page elements stopped working  due to the presence of two ```bootstrap.js``` files in the page. This error was difficult to catch.
Maybe to give the user to choose bootrap package that he wants to use and remove that because of dependencies?

**Comment by jfgodoy** [comment]
this issue can be solved using npm [peerDependencies](http://blog.nodejs.org/2013/02/07/peer-dependencies/)

```
  "peerDependencies": {
    "bootstrap": "^3.4.5"
  }
```

**Comment by stefanocudini** [comment]
@jfgodoy https://github.com/stefanocudini/bootstrap-list-filter/commit/de147390e5b7c072b806dec55e4a9061b965b60a

**Comment by jfgodoy** [comment]
@stefanocudini, I put that script using the last version of bootstrap as example. I think your proyect is compatilbe with old versions of bootstrap. Also remember to remove the bootstrap dependency from `dependencies` property.
