### ISSUE TITLE
[question] showing "no results" when filtering existing elements?

### ISSUE THREAD

**Issue by tconroy** [stefanocudini/bootstrap-list-filter#6]
Hi, 
I'm using bootstrap-list-filter to filter existing list-elements on a page. I have it working great, however if no matches are found, I'd like to display some sort of message like "no results found" .. How do I configure that? Currently it just shows nothing when no results match.

**Comment by jerone** [comment]
This seems to be already possible; https://github.com/stefanocudini/bootstrap-list-filter/blob/master/bootstrap-list-filter.src.js#L41 but not with static datasource.

**Comment by tconroy** [comment]
Yeah I noticed it worked with external sources. Thanks for adding support for static! :+1:
