### ISSUE TITLE
[question ]is there a documentation of the options?

### ISSUE THREAD

**Issue by bwbohl** [stefanocudini/bootstrap-list-filter#7]
Many thanks for this great development.
Is there a more verbose documentation of the option for the searchList than the js code?
I'm trying to insert the items into the list via js but then only get preexisting items filtered...

Help would be appreciated.

Many thanks,
Benjamin

**Comment by jerone** [comment]
:+1: on adding some documentation about all options

**Comment by stefanocudini** [comment]
Options documented:
https://github.com/stefanocudini/bootstrap-list-filter#options

**Comment by stefanocudini** [comment]
Options documented:
https://github.com/stefanocudini/bootstrap-list-filter#options
